import {Platform, StyleSheet} from 'react-native';
import {TypographyVariant} from './Typography.types';
import {ColorPalette} from '../../../config/colorPalette';
import {getScreenHeight} from '../../../helpers/screenSize';
import {Fonts} from '../../../config/fonts';

export const textBaseStyles = StyleSheet.create({
  [TypographyVariant.H1_MEDIUM]: {
    fontSize: 36,
    lineHeight: 44,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.H1_SEMIBOLD]: {
    fontSize: 36,
    lineHeight: 44,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.H1_BOLD]: {
    fontSize: 36,
    lineHeight: 44,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.H1_EXTRABOLD]: {
    fontSize: 36,
    lineHeight: 44,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_EXTRABOLD,
  },
  [TypographyVariant.H2_MEDIUM]: {
    fontSize: 32,
    lineHeight: 40,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.H2_SEMIBOLD]: {
    fontSize: 32,
    lineHeight: 40,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.H2_BOLD]: {
    fontSize: 32,
    lineHeight: 40,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.H2_EXTRABOLD]: {
    fontSize: 32,
    lineHeight: 40,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_EXTRABOLD,
  },
  [TypographyVariant.H3_MEDIUM]: {
    fontSize: 28,
    lineHeight: 36,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.H3_SEMIBOLD]: {
    fontSize: 28,
    lineHeight: 36,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.H3_BOLD]: {
    fontSize: 28,
    lineHeight: 36,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.H3_EXTRABOLD]: {
    fontSize: 28,
    lineHeight: 36,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_EXTRABOLD,
  },
  [TypographyVariant.H4_MEDIUM]: {
    fontSize: 24,
    lineHeight: 32,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.H4_SEMIBOLD]: {
    fontSize: 24,
    lineHeight: 32,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.H4_BOLD]: {
    fontSize: 24,
    lineHeight: 32,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.H4_EXTRABOLD]: {
    fontSize: 24,
    lineHeight: 32,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_EXTRABOLD,
  },
  [TypographyVariant.H5_MEDIUM]: {
    fontSize: 20,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.H5_SEMIBOLD]: {
    fontSize: 20,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.H5_BOLD]: {
    fontSize: 20,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.H5_EXTRABOLD]: {
    fontSize: 20,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_EXTRABOLD,
  },
  [TypographyVariant.H6_MEDIUM]: {
    fontSize: 18,
    lineHeight: 24,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.H6_SEMIBOLD]: {
    fontSize: 18,
    lineHeight: 24,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.H6_BOLD]: {
    fontSize: 18,
    lineHeight: 24,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.H6_EXTRABOLD]: {
    fontSize: 18,
    lineHeight: 24,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_EXTRABOLD,
  },
  [TypographyVariant.PMEDIUM_REGULAR]: {
    fontSize: 16,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PMEDIUM_MEDIUM]: {
    fontSize: 16,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PMEDIUM_SEMIBOLD]: {
    fontSize: 16,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PMEDIUM_BOLD]: {
    fontSize: 16,
    lineHeight: 28,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PSMALL_REGULAR]: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PSMALL_MEDIUM]: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PSMALL_SEMIBOLD]: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PSMALL_BOLD]: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PXSMALL_REGULAR]: {
    fontSize: 12,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PXSMALL_MEDIUM]: {
    fontSize: 12,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PXSMALL_SEMIBOLD]: {
    fontSize: 12,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.PXSMALL_BOLD]: {
    fontSize: 12,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.OVERLINE_SMALL]: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.OVERLINE_MEDIUM]: {
    fontSize: 12,
    lineHeight: 20,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.LMEDIUM_REGULAR]: {
    fontSize: 14,
    lineHeight: 16,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.LMEDIUM_MEDIUM]: {
    fontSize: 14,
    lineHeight: 16,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.LMEDIUM_SEMIBOLD]: {
    fontSize: 14,
    lineHeight: 16,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.LMEDIUM_BOLD]: {
    fontSize: 14,
    lineHeight: 16,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.LMEDIUM_EXTRABOLD]: {
    fontSize: 16,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.LSMALL_REGULAR]: {
    fontSize: 12,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.LSMALL_MEDIUM]: {
    fontSize: 12,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.LSMALL_SEMIBOLD]: {
    fontSize: 12,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.LSMALL_BOLD]: {
    fontSize: 12,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.LXSMALL_REGULAR]: {
    fontSize: 10,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.LXSMALL_MEDIUM]: {
    fontSize: 10,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.LXSMALL_SEMIBOLD]: {
    fontSize: 10,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.LXSMALL_BOLD]: {
    fontSize: 10,
    lineHeight: 14,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  [TypographyVariant.LXXSMALL_REGULAR]: {
    fontSize: 9,
    lineHeight: 12,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_REGULAR,
  },
  [TypographyVariant.LXXSMALL_MEDIUM]: {
    fontSize: 9,
    lineHeight: 12,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
  [TypographyVariant.LXXSMALL_SEMIBOLD]: {
    fontSize: 9,
    lineHeight: 12,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_SEMIBOLD,
  },
  [TypographyVariant.LXXSMALL_BOLD]: {
    fontSize: 9,
    lineHeight: 12,
    fontStyle: 'normal',
    fontFamily: Fonts.POPPINS_BOLD,
  },
  touchable: {
    marginBottom:
      Platform.OS === 'ios' ? -getScreenHeight(0.2) : -getScreenHeight(0.5),
  },
  fontColor: {
    color: ColorPalette.Black,
  },
});
